version: "3"

services:
  bidderhub:
    build: .
    ports:
      - 8080:8080
    environment:
      bidders: http://host.docker.internal:8081, http://host.docker.internal:8082, http://host.docker.internal:8083